export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';

export const CREATE_TASK = 'CREATE_TASK';
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR';
export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR';
export const SET_TASK_TIME = 'SET_TASK_TIME';
export const SET_TASK_TIME_ERROR = 'SET_TASK_TIME_ERROR';
export const SET_TASK_DONE = 'SET_TASK_DONE';
export const SET_TASK_DONE_ERROR = 'SET_TASK_DONE_ERROR';

export const CREATE_TEAM = 'CREATE_TEAM';
export const CREATE_TEAM_ERROR = 'CREATE_TEAM_ERROR';
export const DELETE_TEAM = 'DELETE_TEAM';
export const DELETE_TEAM_ERROR = 'DELETE_TEAM_ERROR';
export const ADD_TEAM = 'ADD_TEAM';
export const ADD_TEAM_ERROR = 'ADD_TEAM_ERROR';

export const ADD_TOAST = 'ADD_TOAST';
export const ADD_TOAST_ERROR = 'ADD_TOAST_ERROR';


export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
